language: python

python:
  - "2.7"

before_script:
  - wget https://commondatastorage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.4.zip -nv
  - unzip -q google_appengine_1.9.4.zip



script:
  - export PYTHONPATH=$PYTHONPATH:google_appengine
  - python runtests.py
